tags: with_gvisor
go_ldflags: "-w -s"
core_version: v1.19.32-tenvpn.1
core_dir: core
core_name: TENVPNCore
lib_name: libclash
output_dir: libclash
helper_dir: services/helper
helper_name: TENVPNHelperService
