script_template: inno_setup.iss
app_id: 08FF098A-B854-4177-B6FA-CBBB8373C8AD
app_name: TENVPN
publisher_name: TENVPN
publisher_url: https://github.com/Chebobakov/tenvpn-client
display_name: TENVPN
executable_name: TENVPN.exe
output_base_file_name: TENVPN.exe
# Resolved against the project root: flutter_distributor turns this into an
# absolute path via Directory.current.
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: ru
  - lang: en
privileges_required: admin
